import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./login/header";
import Login from "./login/login";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Wedmegood",
  description: "Generated by create next app",
};

export default function Page({ children }: Readonly<{ children: ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}
      <div className="bg-[white] h-screen">
      <Header />
      <Login />
      </div>
      </body>
    </html>
  );
}
