import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./login/header";
import Login from "./login/login";
import { ReactNode } from "react";

const inter = Inter({ subsets: ["latin"] });

const Page = ({ children }: { children: ReactNode }) => {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="bg-[white] h-screen">
          <Header />
          <Login />
        </div>
      </body>
    </html>
  );
};

export const metadata: Metadata = {
  title: "Wedmegood",
  description: "Generated by create next app",
};

export default Page;
<<<<<<< HEAD
=======

>>>>>>> e4897d625b53a1a66df952621e42d18c7dd228d5
